### PR TITLE
Add fs.access binding

### PR DESCRIPTION
**Pull request by shyiko**

### CODE REVIEW

**Comment by tschaub** [comment]
Thanks for the contribution @shyiko.  I'll add some `fs.access()` tests and cut a new release with this soon.

**Comment by shyiko** [comment]
@tschaub Thank you!

**Comment by tschaub** [comment]
The docs make it look like [`fs.access()`](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) works on Windows as well.  If anybody knows how that works (without `process.getuid()` and `process.getgid()`), enhancements to `binding.access()` are welcome.

**Comment by tschaub** [comment]
Published as `mock-fs@3.7.0`.

**Pull request merged**
