### PR TITLE
Clear the require cache before overriding fs functions

### LINKED ISSUE #103: Running with tests that don't use mockfs
I had some issues running unit tests (in mocha) with a `mock-fs` setup for a module that was also included in other tested modules, whose tests did not make use of `mock-fs`. This would only happen if the tests that did not use `mock-fs` ran first - so it seemed there was an issue with non-overridden modules being cached.

My solution was to add this to the top of test files that used `mock-fs`:

``` js
// Clear require cache to make sure mock-fs works
Object.keys(require.cache).forEach(function (key) {delete require.cache[key];}); 
```

I'm wondering if there's a better way to do this, or if it would be helpful to add this to the documentation?

### PR DESCRIPTION
**Pull request by tschaub**
This makes things work in cases where another module requires `fs-extra` (or similar) before `mocks-fs` is required.

Fixes #103.

### CODE REVIEW

**Comment by gyandeeps** [comment]
Is this a breaking change?

**Comment by tschaub** [comment]
@gyandeeps - it should not be.  Is there an easy way to reproduce the failure you were seeing?

**Comment by gyandeeps** [comment]
Basically `eslint` unit test started failing with 3.12.0 release. but if I comment out the lines changes in this commit (the cache changes) then it works fine. In eslint we use mock-fs only in 2 modules but all others use real files as of now. But in test which uses mock-fs we do make sure it calls the restore function also.

To be honest I havent bisected a lot to findout the real cause.

**Comment by tschaub** [comment]
Apologies for the trouble @gyandeeps.  I'll try to find time to dig into the failures and make sense of what's going on.  If any other reports come up, or if you would benefit from running tests on Node 7, I'll cut a release that reverts this change.

**Comment by gyandeeps** [comment]
Thanks for help @tschaub . We are planning to start doing node7 testing and for that we need to update the mock-fs. We would like a release of mock-fs with node7 updates but I would totally understand if you have reservations on it. If we can solve this in a easy way i am all of it.
Thanks again for support.

**Comment by not-an-aardvark** [comment]
I've investigated this a bit more. Here's a reproduction case that is a simplification of what our build is doing:

```js
// test.js

require('./foo.js').setValue();

require('mock-fs');

assert(require('./foo.js').getValue() === true);

```


```js
// foo.js

var value = false;

module.exports = {
  modifyValue() {
    value = true;
  },
  getValue() {
    return value;
  }
};
```

This works with `mock-fs@3.11.0` and not with `mock-fs@3.12.0`, because `mock-fs@3.12.0` nukes the `require` cache when it loads.

**Comment by not-an-aardvark** [comment]
I think #103 was occurring due to something like this:

```js
// in fs-extra

module.exports = {
  readFile: require('fs').readFile
};
```

Since `fs-extra` has a reference to the `readFile` function rather than just the `fs` object, mutating the `fs` object wasn't changing the behavior of the `fs-extra` function.

As an alternative to clearing the require cache, have you considered mutating the `process.binding('fs')` object directly? All the `fs` functions depend on the `process.binding('fs')` object, so this would allow you to modify the behavior of the `fs.readFile` function itself, even if another module already had a reference to the function.

**Comment by tschaub** [comment]
@gyandeeps and @not-an-aardvark - I've reverted these changes and published 3.12.1.

@not-an-aardvark - yes, modifying `process.binding('fs')` directly would be a nice alternative.  It would be good to experiment with that approach.

**Comment by tschaub** [comment]
@not-an-aardvark - See #182 for a work-in-progress PR that overrides only `process.binding('fs')`.  This is a nice simplification, but comes with some breaking changes.  It might be possible to avoid these with a bit more work though.

**Pull request merged**
