### PR TITLE
Only override process.binding('fs')

### PR DESCRIPTION
**Pull request by tschaub**
This reworks how the `fs` module is mocked.  Instead of overriding methods on the module itself, only the `process.binding('fs')` methods are replaced.

Possible breaking changes:

 * The `mock.fs()` function has been removed (this could be added back)
 * The object created by `fs.Stats` is no longer an `instanceof fs.Stats` (this could be possible to support again)
 * Lazy `require()` calls don't work consistently (perhaps this can be made to work again too)
 * No more support for Node < 4 (tests are not run there, but things probably still work)

### CODE REVIEW

**Comment by eugef** [comment]
I am using Node 6.3 and Babel to transpile `import` statements.
The current master doesn't work for me.

But this PR works for me, great job @tschaub !

Any plans to release it?

**Comment by tschaub** [comment]
@not-an-aardvark - Yeah, I'm aware that `process.binding('fs')` is not a stable feature.  It turns out that the `mock-fs` binding works with Node 0.8 through 7.  So although there have been Node releases with breaking `fs` changes, I've been able to maintain a single binding that has worked with them all.

@eugef - I haven't had time to address the breaking changes [mentioned above](https://github.com/tschaub/mock-fs/pull/182#issue-186528707).  I'm personally most interested in fixing the `require` issue (making `require` consistently work with the real `fs` even when called lazily).  Not sure which of these will affect the most users.

I'll release a beta and see if we can get some feedback.

**Comment by eugef** [comment]
When it would be released?

**Comment by tschaub** [comment]
You can install `mock-fs@beta` to try it out.

**Pull request merged**
