### PR TITLE
fix: fix the memory leak introduced in nodejs v10 patch

### LINKED ISSUE #302: mock.restore() leaks (no garbage collection)
# Bug Report

Hello,

Unfortunately, it seems that garbage collection is not working after mock.restore().

In my case, I have a collection of files which are pre-loaded. The total size is around 100mb.

The format is:
```jsonc
{
  "/path/dir": {},
  "/path/dir/file.ext": "file content"
}
```

When I call mock.restore(), the expectation is that the memory usage would go down, however it does not.

Re-initializing mock() with the same object causes the memory to go up. Just a few calls to mock/restore puts me over 1.4gb very quickly. I discovered this because GH actions started failing due to exceeding oldspace size for Node 10.

## Workaround

If anyone encounters the same issue, here is my workaround, which uses file caching that we can control

```ts
import { normalizeSlashes } from 'ts-node';
import shell from 'shelljs';
import path from 'path';
import fs from 'fs';
import FileSystem from 'mock-fs/lib/filesystem';
import { default as mock } from 'mock-fs';


/* ***************************************************** */
// Constants
/* ***************************************************** */
const cachedFiles = new Map<string, Buffer>();
const vanillaFiles = cacheDirectories(
  '/path/to/files', 
  '/path/to/otherfiles'
);


/* ***************************************************** */
// Helpers
/* ***************************************************** */
/**
 * Create a DirectoryItems from actual files and directories for mock-fs (uses caching)
 */
function cacheDirectories(...directory: string[]): FileSystem.DirectoryItems {
  const res: FileSystem.DirectoryItems = {};
  for (const dir of directory)
    for (const stat of shell.ls('-RAl', dir) as unknown as (fs.Stats & { name: string })[]) {
      const statPath = normalizeSlashes(path.join(dir, stat.name));
      res[statPath] =
        !stat.isFile() ? {} :
        <ReturnType<typeof mock.file>>(() => {
          const fileData = fs.readFileSync(statPath);
          cachedFiles.set(statPath, fileData);

          return Object.defineProperty(mock.file({ content: '' })(), '_content', {
            get: () => cachedFiles.get(statPath),
            set: (data: any) => cachedFiles.set(statPath, data)
          });
        });
    }

  return res;
}


/* ***************************************************** */
// Exports
/* ***************************************************** */
export function mockFs() {
  mock(vanillaFiles);
}

export function restoreFs() {
  mock.restore();
  cachedFiles.clear();
}
```

# Feature Request
## Access to original `fs`

It would be wonderful to have the ability to access the original `fs` module. Originally, I wanted to do a lazy load solution, which allowed me to only cache files when a readFileSync was called. 

I'm mocking full node projects with node_modules (testing for https://npmjs.com/ts-patch), but many files never get loaded. It would be great to not have to load them.

It's easy to integrate with the above logic, however however, we'd need the ability to read file data from the actual filesystem. The only way I found to do that was by `child_prcoess.spawnSync` to create a new node instance and get the data from the output buffer. This was unfortunately too slow.

TLDR; Would love the have an `fsOriginal` accessible, or, minimally, `readFileSync`, so we could lazy-load and cache

### PR DESCRIPTION
**Pull request by 3cp**
closes #302

### CODE REVIEW

**Comment by nonara** [comment]
Looking into this now. First results were inconclusive. It looked like it was working at first, but one of the threads still climbs over 1gb, which doesn't seem right to me.

So, I'm doing some memory profiling now. Going to examine heap snapshots. Will let you know!

**Comment by nonara** [comment]
Looks good!

I pre-loaded it with one large file (149,382,687 bytes)

This is the heap comparison before and after `mock.restore()`.

image

For good measure, I also mocked & restored repeatedly with the same data about 6 times in a row. Reported memory use in task manager stayed the same.

Thanks for the fast work! BTW, Have you had a chance to look at my PR?

**Comment by 3cp** [comment]
@tschaub can we merge this?

**Comment by tschaub** [comment]
@3cp - yes please.  Are you able to?  Every time I get the notification, I’m not on a device that is allowed to merge with the failed test.

**Comment by 3cp** [comment]
I cannot. Tried to skip win32 node 12 in CI, but GitHub is not happy about it, maybe I missed some config.

**Comment by tschaub** [comment]
Thanks for the fix, @3cp.  Sorry it took so long to get in.

**Comment by Johnhhorton** [comment]
Can we get a release 🙏 ?

**Pull request merged**
