### PR TITLE
fix: Replace nextTick by setImmediate.

### LINKED ISSUE #352: Different behavior with yauzl
The [yauzl](https://github.com/thejoshwolfe/yauzl) library has a different behavior with mock-fs.

```JavaScript
import mock from "mock-fs";
import yauzl from "yauzl";

if (process.argv.includes("mock")) {
    mock({ "baz.zip": mock.load("baz.zip") });
}

const zipfile = await new Promise((resolve, reject) => {
    yauzl.open("baz.zip", (err, zipfile) => {
        if (err) reject(err);
        resolve(zipfile);
    });
});
zipfile.on("error", (err) => console.log("error", err));
zipfile.on("entry", (entry) => console.log("entry", entry.fileName));
zipfile.on("end", () => console.log("end"));
```

The above code prints :

- without the _mock_ argument: `entry foo.txt` and `end`
- with the _mock_ argument : `end`

I think the problem is that mock-fs does not call IO and returns the result directly ([_Event Loop_](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/)). Because without the promise, the behavior is the same.

```JavaScript
yauzl.open("baz.zip", (err, zipfile) => {
    if (err) throw err;
    zipfile.on("error", (err) => console.log("error", err));
    zipfile.on("entry", (entry) => console.log("entry", entry.fileName));
    zipfile.on("end", () => console.log("end"));
});
```

To reproduce the problem:

- Download and unzip [testcase.zip](https://github.com/tschaub/mock-fs/files/8177037/testcase.zip)
- `npm install`
- `node fail.js`
- `node fail.js mock`

### PR DESCRIPTION
**Pull request by regseb**
Replace `process.nextTick()` by `setImmediate()` to be closer to the reality of asynchronous methods. This pull request fixes #352 testcase with _yauzl_.

### CODE REVIEW

**Comment by 3cp** [comment]
The CI shows this fix only works for Nodejs v16+.
You can try to add a condition to test against nodejs version.

**Comment by regseb** [comment]
I replaced the `nextTick` only for the promise and it seems to work on all versions of Node. Maybe the callbacks are executed directly after, while the promises are executed on the next event loop.

**Comment by 3cp** [comment]
@tschaub can you review this? I am not sure about the side effect of this change.

**Comment by regseb** [comment]
I tested mock-fs with the latest version _5.3.0_ and the problem is still there.

- `index.js`

  ```javascript
  import mock from "mock-fs";
  import yauzl from "yauzl";

  if (!process.argv.includes("without-mock")) {
      mock({ "foo.zip": mock.load("foo.zip") });
  }

  // Test with setImmediate.
  yauzl.open("foo.zip", (err, zipfile) => {
      if (err) throw err;
      setImmediate(() => {
          zipfile.on("error", (err) => console.log("[setImmediate] error", err));
          zipfile.on("entry", (entry) => console.log("[setImmediate] entry", entry.fileName));
          zipfile.on("end", () => console.log("[setImmediate] end"));
      });
  });

  // Wait one second between the two tests.
  await new Promise((r) => setTimeout(r, 1000));

  // Test with Promise.
  const zipfile = await new Promise((resolve, reject) => {
      yauzl.open("foo.zip", (err, zipfile) => {
          if (err) reject(err);
          resolve(zipfile);
      });
  });
  zipfile.on("error", (err) => console.log("[Promise] error", err));
  zipfile.on("entry", (entry) => console.log("[Promise] entry", entry.fileName));
  zipfile.on("end", () => console.log("[Promise] end"));
  ```

- `package.json`

  ```json
  {
      "name": "testcase",
      "version": "1.0.0",
      "type": "module",
      "dependencies": {
          "mock-fs": "5.3.0",
          "yauzl": "3.1.3"
      }
  }
  ```

1. `npm install`
2. `zip foo.zip package.json` (or zip `package.json` with an other tool)
3. `node index.js`
   - Current:

     > [setImmediate] end
     > [Promise] end

   - Expected:

     > [setImmediate] entry package.json
     > [setImmediate] end
     > [Promise] entry package.json
     > [Promise] end

---

@tschaub Can you review this PR to fix the problem?

**Pull request merged**
