### PR TITLE
Implement binding.writeBuffers()

### LINKED ISSUE #88: Issues with buffers
Hey there,
first of all, thanks for the module, really enjoying it.

I have a module that does some piping (fetches files and directly saves them), however, when testing it, it fails with this error:
```
  1) downloading Nodes should download a specific version:
     Uncaught TypeError: binding.writeBuffers is not a function
      at writev (node_modules/mock-fs/node/fs-5.0.0.js:1962:11)
      at WriteStream._writev (node_modules/mock-fs/node/fs-5.0.0.js:1984:3)
      at doWrite (_stream_writable.js:290:12)
      at clearBuffer (_stream_writable.js:380:5)
      at onwrite (_stream_writable.js:331:7)
      at WritableState.onwrite (_stream_writable.js:89:5)
      at node_modules/mock-fs/node/fs-5.0.0.js:1946:5
      at wrapper (node_modules/mock-fs/node/fs-5.0.0.js:667:5)
      at node_modules/mock-fs/lib/binding.js:37:9
```
Could this be because the dependencies I used (__got__ and __tar.gz__) are not compatible? The code, if needed, can be found [here](https://github.com/maxrimue/automagic/blob/master/test/index.js#L49).

Thanks

### PR DESCRIPTION
**Pull request by tschaub**
This adds an implementation for `binding.writeBuffers()`.  The `fs` uses a new `binding.writeBuffers()` method in implementing the stream's `_writev` method.  The `_writev` method in turn looks to be called when there is a buffered write request.  In Node >= 0.12, this happens when calling `write` on a corked stream.  So the integration tests for the new `writeBuffers()` method corks, writes to, and then uncorks a write stream.

Fixes #88.

### CODE REVIEW

**Comment by jeresig** [comment]
@tschaub I just checked out this pull request and ran it against my reduced test case and it passed. Thank you!

**Comment by jeresig** [comment]
Fantastic, thank you! :+1:

**Comment by tschaub** [comment]
Published as `mock-fs@3.8.0`.  Thanks for the help narrowing this down.

**Comment by jeresig** [comment]
@tschaub no problem! I just pulled `mock-fs@3.8.0` into my app and confirmed that it fixed the issue I was seeing. Thank you again for your work and great module!

**Pull request merged**
